version: '3'
services:
  localstack:
    container_name: ${LOCALSTACK_DOCKER_NAME-localstack_sam_one}
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-southeast-2
      - DATA_DIR=/tmp/localstack/data